# typed: false
# frozen_string_literal: true

# Auto-generated by scripts/publish-tap.sh — DO NOT EDIT BY HAND.
# 이 파일은 메인 저장소의 publish-tap.sh 가 자동 생성합니다. 수동 편집 금지.
class OpenclawWorkspace < Formula
  desc "macOS self-host automation for OpenClaw (one-line install/maintain/uninstall)"
  homepage "https://github.com/GoGoComputer/openclaw-workspace"
  url "https://github.com/GoGoComputer/openclaw-workspace/archive/refs/tags/v0.1.7.tar.gz"
  sha256 "412a570c5983c9ba1fe9c7a69d69b7df5944802352e50b79714ab9382d88219d"
  license "MIT"
  version "0.1.7"

  depends_on :macos
  depends_on "bash" => :recommended

  def install
    libexec.install Dir["openclaw-mgr/*"]
    libexec.install Dir["openclaw-mgr/.env.example"] if File.exist?("openclaw-mgr/.env.example")

    (bin/"openclaw").write <<~SH
      #!/bin/bash
      exec "#{libexec}/openclaw" "$@"
    SH
    chmod 0755, bin/"openclaw"

    doc.install "README.md", "README.en.md", "LICENSE", "SECURITY.md"
    (doc/"docs").install Dir["docs/*"]
  end

  def caveats
    <<~EOS
      🦞 openclaw-workspace installed!

      Run the interactive menu (auto-detects Korean/English):
        openclaw

      Or invoke subcommands directly:
        openclaw doctor          # diagnose
        openclaw install         # auto-install Docker / Ollama / OpenClaw

      First run auto-creates ~/.openclaw-mgr/.env from the template.
      State is kept in ~/.openclaw-mgr/   (survives brew upgrades).

      Docker Desktop and Ollama are auto-installed by 'openclaw install'
      if missing — no need to brew them yourself.

      Docs: #{HOMEBREW_PREFIX}/share/doc/openclaw-workspace/
      Repo: https://github.com/GoGoComputer/openclaw-workspace
    EOS
  end

  test do
    assert_match "openclaw-mgr", shell_output("#{bin}/openclaw --version")
    help = shell_output("#{bin}/openclaw help")
    %w[doctor install start stop logs update backup restore schedule network clean uninstall].each do |sub|
      assert_match sub, help
    end
  end
end
